apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: instana-selfhosted-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: instana-selfhosted-operator
subjects:
- kind: ServiceAccount
  name: instana-selfhosted-operator
  namespace: instana-operator