apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: zookeeper
  namespace: instana-core
subsets:
- addresses:
  - ip: 9.112.255.99
  ports:
  - name: tcp
    port: 2181
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: kafka
  namespace: instana-core
subsets:
- addresses:
  - ip: 9.112.255.99
  ports:
  - name: tcp
    port: 9092
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: elasticsearch
  namespace: instana-core
subsets:
- addresses:
  - ip: 9.112.255.99
  ports:
  - name: tcp
    port: 9200
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: clickhouse
  namespace: instana-core
subsets:
- addresses:
  - ip: 9.112.255.99
  ports:
  - name: tcp
    port: 9000
    protocol: TCP
  - name: http
    port: 8123
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: cockroachdb
  namespace: instana-core
subsets:
- addresses:
  - ip: 9.112.255.99
  ports:
  - name: tcp
    port: 26257
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: cassandra
  namespace: instana-core
subsets:
- addresses:
  - ip: 9.112.255.99
  ports:
  - name: tcp
    port: 9042
    protocol: TCP