apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: cassandra
  namespace: instana-core
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 9042
    protocol: TCP
    targetPort: 9042
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: cockroachdb
  namespace: instana-core
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 26257
    protocol: TCP
    targetPort: 26257
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: clickhouse
  namespace: instana-core
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8123
    protocol: TCP
    targetPort: 8123
  - name: tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: elasticsearch
  namespace: instana-core
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: tcp
    port: 9300
    protocol: TCP
    targetPort: 9300
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: kafka
  namespace: instana-core
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 9092
    protocol: TCP
    targetPort: 9092
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    application: instana
    group: operator
  name: zookeeper
  namespace: instana-core
spec:
  clusterIP: None
  ports:
  - name: tcp
    port: 2181
    protocol: TCP
    targetPort: 2181
status:
  loadBalancer: {}